// Last updated: 2/6/2026, 5:18:01 PM
#include <iostream>
#include <vector>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <climits>

using namespace std;

class Solution {
public:
    long long minimumCost(string source, string target, vector<string>& original, vector<string>& changed, vector<int>& cost) {
            // 1. Map all unique strings to integer IDs
                    unordered_map<string, int> strToId;
                            int idCounter = 0;
                                    
                                            auto getId = [&](const string& s) {
                                                        if (strToId.find(s) == strToId.end()) {
                                                                        strToId[s] = idCounter++;
                                                                                    }
                                                                                                return strToId[s];
                                                                                                        };

                                                                                                                // Collect distinct lengths to optimize the DP inner loop
                                                                                                                        unordered_set<int> lengths;
                                                                                                                                for (const string& s : original) {
                                                                                                                                            lengths.insert(s.length());
                                                                                                                                                        getId(s);
                                                                                                                                                                }
                                                                                                                                                                        for (const string& s : changed) {
                                                                                                                                                                                    getId(s);
                                                                                                                                                                                            }

                                                                                                                                                                                                    int numNodes = strToId.size();
                                                                                                                                                                                                            
                                                                                                                                                                                                                    // 2. Initialize Distance Matrix (Adjacency Matrix)
                                                                                                                                                                                                                            vector<vector<long long>> dist(numNodes, vector<long long>(numNodes, LLONG_MAX));
                                                                                                                                                                                                                                    for (int i = 0; i < numNodes; i++) dist[i][i] = 0;

                                                                                                                                                                                                                                            for (size_t i = 0; i < original.size(); ++i) {
                                                                                                                                                                                                                                                        int u = getId(original[i]);
                                                                                                                                                                                                                                                                    int v = getId(changed[i]);
                                                                                                                                                                                                                                                                                dist[u][v] = min(dist[u][v], (long long)cost[i]);
                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                // 3. Floyd-Warshall Algorithm for All-Pairs Shortest Path
                                                                                                                                                                                                                                                                                                        for (int k = 0; k < numNodes; ++k) {
                                                                                                                                                                                                                                                                                                                    for (int i = 0; i < numNodes; ++i) {
                                                                                                                                                                                                                                                                                                                                    if (dist[i][k] == LLONG_MAX) continue; // Optimization
                                                                                                                                                                                                                                                                                                                                                    for (int j = 0; j < numNodes; ++j) {
                                                                                                                                                                                                                                                                                                                                                                        if (dist[k][j] == LLONG_MAX) continue;
                                                                                                                                                                                                                                                                                                                                                                                            dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j]);
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                        // 4. Dynamic Programming
                                                                                                                                                                                                                                                                                                                                                                                                                                                int n = source.length();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        vector<long long> dp(n + 1, LLONG_MAX);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                dp[0] = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (int i = 0; i < n; ++i) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (dp[i] == LLONG_MAX) continue;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Case A: Characters match, 0 cost to move to next index
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (source[i] == target[i]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            dp[i + 1] = min(dp[i + 1], dp[i]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Case B: Convert a substring starting at i
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (int len : lengths) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (i + len > n) continue;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                string subS = source.substr(i, len);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                string subT = target.substr(i, len);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Check if both substrings are known nodes in our graph
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                auto itS = strToId.find(subS);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                auto itT = strToId.find(subT);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (itS != strToId.end() && itT != strToId.end()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int u = itS->second;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int v = itT->second;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (dist[u][v] != LLONG_MAX) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dp[i + len] = min(dp[i + len], dp[i] + dist[u][v]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (dp[n] == LLONG_MAX) ? -1 : dp[n];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };